apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: messenger
  namespace: messenger
  labels:
    app: messenger
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: messenger
  targetCPUUtilizationPercentage: 80
