apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fuctional-testing
  namespace: messenger
spec:
  args:
  - name: repo-url
  - name: folder-test
  - name: base-url
  - name: commit-hash
  - name: functional-version
    value: "1"
  metrics:
  - name: functional-testing
    provider:
      job:
        metadata:
          labels:
            app: functionaltest
        spec:
          backoffLimit: 1
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
              - name: functionaltest
                image: quinont/fuctional-testing:{{args.functional-version}}
                env:
                - name: REPO_URL
                  value: "{{args.repo-url}}"
                - name: FOLDER_TEST
                  value: "{{args.folder-test}}"
                - name: BASE_URL
                  value: "{{args.base-url}}"
                - name: COMMIT_HASH
                  value: "{{args.commit-hash}}"
              restartPolicy: Never
